import { NextResponse } from "next/server";
export async function POST(req:Request){
 const x=await req.json(); const feed:{[k:string]:number}={"Dairy wastewater":1,"Cow manure":.96,"Food waste":1.14,"Brewery":1.08,"Paper mill":.88}; const f=feed[x.feedstock]??1;
 const tempScore=Math.max(.65,1-Math.abs(x.temperature-36.8)*.055); const phScore=Math.max(.55,1-Math.abs(x.ph-7.15)*.34); const hrtScore=Math.max(.65,1-Math.abs(x.hrt-23)*.018); const olrScore=Math.max(.58,1-Math.abs(x.olr-3.1)*.10); const mixScore=Math.max(.72,1-Math.abs(x.mixing-55)*.006);
 const baseline=Math.max(22,x.feedRate*.061*f); const factor=tempScore*phScore*hrtScore*olrScore*mixScore; const biogas=baseline*(.92+.34*factor); const methanePct=Math.min(70,55+12*phScore*tempScore+1.5*(f-1)); const methane=biogas*methanePct/100; const electricity=methane*9.97*.36; const improvement=(biogas/baseline-1)*100; const codRemoval=Math.min(94,60+26*factor); const stability=Math.min(98,52+45*Math.min(phScore,tempScore,hrtScore,olrScore)); const confidence=Math.min(96,72+20*factor); const pressure=15+biogas*.075; const h2s=Math.max(45,520-190*phScore-120*tempScore); const carbon=electricity*.000708;
 const recs=[]; if(x.ph<7.05)recs.push({title:`Increase pH toward 7.10`,detail:"Dose alkalinity gradually and monitor VFA response.",impact:Math.min(7,(7.1-x.ph)*18),tone:"up"}); else if(x.ph>7.35)recs.push({title:"Reduce alkalinity dosing",detail:"Bring pH toward the stable methanogenic range.",impact:Math.min(5,(x.ph-7.2)*13),tone:"down"});
 if(x.temperature<36.3)recs.push({title:"Increase digester temperature",detail:"Ramp slowly; avoid a change greater than 1°C per day.",impact:Math.min(8,(36.8-x.temperature)*2.1),tone:"up"}); else if(x.temperature>38)recs.push({title:"Reduce heating setpoint",detail:"Current temperature may reduce mesophilic stability.",impact:Math.min(7,(x.temperature-37)*2),tone:"down"});
 if(x.olr<2.8)recs.push({title:"Increase feed rate carefully",detail:"Raise OLR in small steps while watching VFA and gas response.",impact:Math.min(6,(3.1-x.olr)*4),tone:"up"}); else if(x.olr>3.8)recs.push({title:"Reduce organic loading",detail:"Protect the digester from acidification and shock loading.",impact:Math.min(8,(x.olr-3.4)*5),tone:"down"});
 if(x.mixing<50)recs.push({title:"Increase intermittent mixing",detail:"Improve substrate contact without excessive parasitic load.",impact:Math.min(4,(55-x.mixing)*.25),tone:"up"});
 if(!recs.length)recs.push({title:"Hold current setpoints",detail:"Conditions are close to the modeled operating optimum.",impact:1.2,tone:"up"});
 recs.push({title:"Validate with a 24-hour trial",detail:"Confirm the projected gain against an equivalent baseline window.",impact:Math.max(1,improvement*.08),tone:"up"});
 const forecast=Array.from({length:12},(_,i)=>biogas*(.91+i*.009+Math.sin(i*1.45)*.018));
 return NextResponse.json({biogas,methanePct,methane,electricity,carbon,codRemoval,stability,confidence,improvement,pressure,h2s,recommendations:recs.slice(0,4),forecast});
}
