import {NextResponse} from "next/server";
export async function POST(req:Request){const {question,inputs,prediction}=await req.json();const q=String(question).toLowerCase();let answer="";
 if(q.includes("ph"))answer=`Your pH is ${inputs.ph}. The prototype knowledge base targets roughly 7.0–7.4, with about 7.1–7.2 used for optimization. ${inputs.ph<7?"Increase alkalinity gradually and check VFA before adding feed.":inputs.ph>7.4?"Reduce dosing and check ammonia inhibition.":"It is inside the modeled safe band."}`;
 else if(q.includes("methane")||q.includes("increase"))answer=`The strongest controllable levers in this scenario are pH, temperature, organic loading and mixing. ${prediction?`The model currently predicts ${prediction.methanePct.toFixed(1)}% CH₄ and ${prediction.methane.toFixed(1)} m³ CH₄/day.`:"Run a prediction and I’ll rank changes for the current inputs."}`;
 else if(q.includes("explain")||q.includes("prediction"))answer=prediction?`The linear prototype combines feed rate and feedstock with distance-to-target scores for temperature, pH, OLR, HRT and mixing. It predicts ${prediction.biogas.toFixed(1)} m³/day biogas and ${prediction.electricity.toFixed(1)} kWh/day. Electricity uses methane × 9.97 kWh/m³ × 36% conversion efficiency.`:"No current result is available. Run AI prediction first, then ask me to explain it.";
 else if(q.includes("hrt")||q.includes("retention"))answer="The supplied validation runs use about 22–26 days. The hours-scale workbook is explicitly experimental and not site-validated, so this prototype does not recommend hours-scale HRT for full digestion.";
 else if(q.includes("carbon"))answer=prediction?`Estimated avoided grid emissions are ${prediction.carbon.toFixed(2)} tCO₂e/day, based on the predicted electricity and a configurable prototype factor of 0.708 kgCO₂e/kWh. Replace that factor with the project location’s approved value.`:"Carbon reduction is calculated after a prediction from electricity generated and the configured grid factor.";
 else if(q.includes("data")||q.includes("source"))answer="The prototype knowledge base covers the 1,000-row synthetic SCADA template, 10 validation runs, 10 optimization scenarios, and literature-informed/synthetic short-HRT scenarios. It clearly treats them as demo evidence, not live site measurements.";
 else answer=`For ${inputs.feedstock.toLowerCase()}, focus on stable pH, temperature, loading and mixing. Run the prediction to receive input-specific actions. I can also explain methane, electricity, carbon, HRT, or the source data.`;
 return NextResponse.json({answer,sources:["SCADA template","10-run validation","Optimization scenarios","Short-HRT scenarios"]});}
