"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

type Inputs = { feedstock:string; feedRate:number; temperature:number; ph:number; olr:number; hrt:number; codIn:number; vfa:number; mixing:number };
type OptimizationTarget = { label:string; value:number };
type Prediction = { biogas:number; methanePct:number; methane:number; electricity:number; carbon:number; codRemoval:number; stability:number; confidence:number; improvement:number; pressure:number; h2s:number; generatorKw:number; optimizationTargets:OptimizationTarget[]; overallBenefit:number; benefitTrend:number[]; recommendations:{title:string;detail:string;impact:number;tone:string}[]; forecast:number[]; bestSetpoints:{feedRate:number;temperature:number;ph:number;olr:number;hrt:number;codIn:number;vfa:number;mixing:number}; agentMessage:string; modelName:string; modelFit:string; outOfRange:boolean; confidenceMeaning?:string };
type AuthUser = { username:string; role:"admin"|"user" };
type Health = { status:string; checkedAt:string; readiness:number; readyChecks:number; totalChecks:number; checks:{key:string;label:string;ready:boolean;weight:number}[]; services:{api:string;model:string;rag:string;auth:string}; knowledge:{workbooks:number;chunks:number}; model:{name:string;version:string;fit:string;inputMode:string} };

const initial: Inputs = { feedstock:"Dairy WW", feedRate:846, temperature:35, ph:7.1, olr:3.5, hrt:22, codIn:7000, vfa:1100, mixing:50 };

const nav = ["Executive Overview","AI Intelligence","Digital Twin","IoT & Sensors","AI Optimization","Prediction Center","Explainable AI","Data & Audit","Settings"];
const futureNav = new Set(["IoT & Sensors"]);
const navTargets:Record<string,string> = {"Executive Overview":"executive-overview","AI Intelligence":"ai-optimization","Digital Twin":"digital-twin","AI Optimization":"ai-optimization","Prediction Center":"prediction-center","Data & Audit":"data-audit"};
const quickQuestions = ["What are the best setpoints?","Explain this prediction","Is my pH safe?"];

export default function Home(){
  const [auth,setAuth]=useState<AuthUser|null>(null); const [authChecking,setAuthChecking]=useState(true);
  const [loginUsername,setLoginUsername]=useState(""); const [loginPassword,setLoginPassword]=useState("");
  const [loginBusy,setLoginBusy]=useState(false); const [loginError,setLoginError]=useState("");
  const [health,setHealth]=useState<Health|null>(null); const [healthError,setHealthError]=useState(false);
  const [settingsOpen,setSettingsOpen]=useState(false); const [now,setNow]=useState(new Date());
  const [inputs,setInputs]=useState(initial); const [result,setResult]=useState<Prediction|null>(null);
  const [loading,setLoading]=useState(false); const [active,setActive]=useState("Executive Overview");
  const [chatOpen,setChatOpen]=useState(false); const [question,setQuestion]=useState("");
  const [messages,setMessages]=useState<{role:string;text:string}[]>([{role:"ai",text:"I’m Aqua Copilot. Ask me about this plant, the prediction, or ways to improve performance."}]);
  const [chatBusy,setChatBusy]=useState(false); const [history,setHistory]=useState<{time:string;biogas:number;electricity:number}[]>([]);
  const [lastRunInputs,setLastRunInputs]=useState<Inputs|null>(null);
  const [detailsOpen,setDetailsOpen]=useState(false);
  const [presentedResultKey,setPresentedResultKey]=useState<string|null>(null);
  const [predictionError,setPredictionError]=useState("");
  const autoRun=useRef(false);

  const refreshHealth=async()=>{try{const response=await fetch("/api/health",{cache:"no-store"});if(response.status===401){setAuth(null);return;}if(!response.ok)throw new Error();setHealth(await response.json());setHealthError(false);}catch{setHealthError(true);}};
  const predict=async()=>{ const previousRun=result&&lastRunInputs?{prediction:result,inputs:lastRunInputs}:null; setLoading(true); setResult(null); setPredictionError("");
    try {
    const [res]=await Promise.all([fetch("/api/predict",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...inputs,previousRun})}),new Promise(r=>setTimeout(r,650))]);
    if(res.status===401){setAuth(null);throw new Error("Your session expired. Please sign in again.");}
    const data=await res.json(); if(!res.ok)throw new Error(data.error||"Prediction service is unavailable."); setResult(data); setLastRunInputs({...inputs}); setHistory(h=>[{time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}),biogas:data.biogas,electricity:data.electricity},...h].slice(0,4));
    } catch(error) { setPredictionError(error instanceof Error?error.message:"Prediction service is unavailable."); } finally { setLoading(false); }
  };
  useEffect(()=>{let active=true;fetch("/api/auth/session",{cache:"no-store"}).then(async response=>{if(!active)return;if(response.ok){const data=await response.json();setAuth(data.user);}setAuthChecking(false);}).catch(()=>setAuthChecking(false));const clock=window.setInterval(()=>setNow(new Date()),60000);return()=>{active=false;window.clearInterval(clock);};},[]);
  useEffect(()=>{if(!auth)return;refreshHealth();const monitor=window.setInterval(refreshHealth,30000);if(!autoRun.current){autoRun.current=true;predict();}return()=>window.clearInterval(monitor);},[auth]);
  const login=async(event:FormEvent)=>{event.preventDefault();setLoginBusy(true);setLoginError("");try{const response=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:loginUsername,password:loginPassword})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Login failed.");autoRun.current=false;setAuth(data.user);setLoginPassword("");}catch(error){setLoginError(error instanceof Error?error.message:"Login failed.");}finally{setLoginBusy(false);}};
  const logout=async()=>{await fetch("/api/auth/logout",{method:"POST"});setAuth(null);setHealth(null);setResult(null);setHistory([]);setSettingsOpen(false);autoRun.current=false;};
  const update=(key:keyof Inputs,value:string)=>setInputs(v=>({...v,[key]:key==="feedstock"?value:Number(value)}));
  const openCopilot=()=>{setChatOpen(true);if(result&&lastRunInputs){const key=JSON.stringify(lastRunInputs);if(key!==presentedResultKey){setMessages(messages=>[...messages,{role:"ai",text:result.agentMessage}]);setPresentedResultKey(key);}}};
  const handleNav=(name:string)=>{const locked=auth?.role!=="admin"&&["Data & Audit","Settings"].includes(name);if(futureNav.has(name)||locked)return;setActive(name);if(name==="Explainable AI"){openCopilot();return;}if(name==="Settings"){setSettingsOpen(true);return;}document.getElementById(navTargets[name]??"executive-overview")?.scrollIntoView({behavior:"smooth",block:"start"});};
  const applyBestSetpoints=()=>{if(!result)return; setInputs(v=>({...v,...result.bestSetpoints})); setMessages(m=>[...m,{role:"ai",text:"I applied the best modeled scenario setpoints to the form. Run the prediction again to compare them with your prior input."}]);};
  const ask=async(e?:FormEvent,q?:string)=>{e?.preventDefault(); const text=(q??question).trim(); if(!text)return; const chatHistory=[...messages.slice(-5),{role:"user",text}]; const predictionForChat=result&&lastRunInputs&&["feedstock","feedRate","temperature","ph","olr","hrt","codIn","vfa","mixing"].every(key=>inputs[key as keyof Inputs]===lastRunInputs[key as keyof Inputs])?result:null; setMessages(m=>[...m,{role:"user",text}]);setQuestion("");setChatBusy(true);
    try { const res=await fetch("/api/copilot",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:text,inputs,prediction:predictionForChat,history:chatHistory})}); if(res.status===401){setAuth(null);throw new Error();} const data=await res.json();
      const evidence=Array.isArray(data.sources)&&data.sources.length?`\n\nEvidence: ${data.sources.slice(0,3).join("; ")}`:""; setMessages(m=>[...m,{role:"ai",text:`${data.answer||"I couldn't complete that answer."}${evidence}`}]);
    } catch { setMessages(m=>[...m,{role:"ai",text:"I couldn't reach the knowledge service. Please try again in a moment."}]); } finally { setChatBusy(false); }
  };
  const points=useMemo(()=>result?.forecast?.length?result.forecast.map((v,i)=>`${i*(100/(result.forecast.length-1))},${90-(v/Math.max(...result.forecast))*68}`).join(" "):"",[result]);
  const benefitValues=result?.benefitTrend??[];
  const benefitPoints=useMemo(()=>{const min=Math.min(...benefitValues),max=Math.max(...benefitValues),span=max-min||1;return benefitValues.map((value,index)=>`${index*(100/(benefitValues.length-1))},${34-((value-min)/span)*27}`).join(" ")},[benefitValues]);

  if(authChecking)return <div className="auth-loading"><span className="spinner"></span><b>Securing Aquaivolt workspace…</b></div>;
  if(!auth)return <LoginScreen username={loginUsername} password={loginPassword} busy={loginBusy} error={loginError} onUsername={setLoginUsername} onPassword={setLoginPassword} onSubmit={login}/>;

  return <main className="shell">
    <aside className="sidebar">
      <div className="brand"><span className="drop">◒</span><div><b>AQUAIVOLT</b><small>AI PLATFORM</small></div></div>
      <nav>{nav.map((n,i)=>{const future=futureNav.has(n);const locked=auth.role!=="admin"&&["Data & Audit","Settings"].includes(n);const disabled=future||locked;return <button key={n} className={`nav ${disabled?(locked?"locked":"future"):"available"} ${active===n?"active":""}`} onClick={()=>handleNav(n)} disabled={disabled} title={future?"Planned IoT module":locked?"Admin access required":`Open ${n}`}><span>{["⌂","✦","♙","◉","✥","◇","◎","▦","⚙"][i]}</span>{n}{disabled&&<small>{locked?"ADMIN":"SOON"}</small>}</button>})}</nav>
      <button className="copilot-mini" onClick={openCopilot}><span className="robot">✦</span><b>AI Copilot Assistant</b><small>Ask about performance, predictions or optimization.</small><em>Start chat →</em></button>
      <div className="copyright">AQUAIVOLT © 2026<br/><small>Prototype • Synthetic data</small></div>
    </aside>

    <section className="workspace" id="executive-overview">
      <header><div><h1>AI Command Center</h1><p>Smart Biogas Optimization & Digital Twin Platform</p></div><div className="header-actions"><span className={`online ${healthError?"degraded":""}`}>● &nbsp; {healthError?"Health check unavailable":health?"System Online":"Checking system"}</span><span className="date">◫ &nbsp; {now.toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})} · {now.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</span><button className="ai-btn" onClick={openCopilot}>✦ &nbsp; AI Copilot</button><button className="account-chip" onClick={()=>auth.role==="admin"?setSettingsOpen(true):logout()} title={auth.role==="admin"?"Open admin settings":"Sign out"}><span>{auth.username.slice(0,2).toUpperCase()}</span><b>{auth.username}<small>{auth.role}</small></b></button></div></header>

      <section className="kpis">
        <Kpi label="Prototype Readiness" value={health?`${health.readiness}%`:"—"} color="#1e87f0" note={health?`${health.readyChecks}/${health.totalChecks} systems ready`:"Checking services"}/>
        <Kpi label="Scenario Coverage" value={result?`${result.confidence.toFixed(0)}%`:"—"} color="#6d28d9" note={result?"Input-space validity score":"Awaiting prediction"}/>
        <Kpi label="Digital Twin" value={loading?"RUN":result?"ACTIVE":"READY"} color="#18a957" note={loading?"Simulating plant":result?`Model v${health?.model.version??"—"}`:(health?.model.inputMode??"Manual input")}/>
        <Kpi label="Optimization Gain" value={result?`${result.improvement>=0?"+":""}${result.improvement.toFixed(1)}%`:"—"} color="#f97316" note={result?"vs. modeled baseline":"Awaiting prediction"}/>
      </section>

      <section className="main-grid">
        <div className="card input-card" id="digital-twin"><Title title="PLANT INPUT & DIGITAL TWIN" badge={(health?.model.inputMode??"MANUAL INPUT").toUpperCase()}/>
          <div className="input-layout"><div className="form-grid">
            <Field label="Feedstock" value={inputs.feedstock} onChange={v=>update("feedstock",v)} options={["Dairy WW","Cow Manure","Food Waste","Brewery","Paper Mill","Mixed Waste"]}/>
            <Field label="Feed rate" value={inputs.feedRate} unit="kg VS/d" onChange={v=>update("feedRate",v)} min={820} max={870}/>
            <Field label="Temperature" value={inputs.temperature} unit="°C" onChange={v=>update("temperature",v)} min={34.08} max={38.87} step="0.1"/>
            <Field label="pH level" value={inputs.ph} onChange={v=>update("ph",v)} min={6.82} max={7.58} step="0.01"/>
            <Field label="Organic loading" value={inputs.olr} unit="kg COD/m³·d" onChange={v=>update("olr",v)} min={1.55} max={6.38} step="0.1"/>
            <Field label="Retention time" value={inputs.hrt} unit="days" onChange={v=>update("hrt",v)} min={15.45} max={34.62} step="0.1"/>
            <Field label="COD input" value={inputs.codIn} unit="mg/L" onChange={v=>update("codIn",v)} min={3205} max={11864}/>
            <Field label="VFA" value={inputs.vfa} unit="mg/L" onChange={v=>update("vfa",v)} min={251} max={2963}/>
            <Field label="Mixer speed" value={inputs.mixing} unit="RPM" onChange={v=>update("mixing",v)} min={20} max={79}/>
          </div><div className="twin-wrap"><div className={`twin ${loading?"working":""}`}><div className="pipe"></div><div className="dome"><span>AQUAIVOLT</span></div><div className="tank"><i></i><i></i><i></i><div className="liquid"></div></div><div className="base"></div></div><p>{loading?"AI agent is simulating outcomes…":"Digital twin ready"}</p></div></div>
          <button className="predict" onClick={predict} disabled={loading}>{loading?<><span className="spinner"></span> Agent analyzing plant conditions…</>:<>✦ Run AI prediction</>}</button>{predictionError&&<p className="inline-error">{predictionError}</p>}
        </div>

        <div className="card optimization" id="ai-optimization"><Title title="AI OPTIMIZATION ENGINE" badge={result?"LIVE REPORT":"AWAITING INPUT"}/>
          {loading?<AgentSteps/>:result?<OptimizationReport result={result} benefitPoints={benefitPoints} onDetails={()=>setDetailsOpen(true)}/>:<div className="empty"><span>✦</span><b>Ready to optimize</b><p>Enter current plant conditions and run a prediction. Every report panel will refresh from the new scenario.</p></div>}
        </div>
      </section>

      <section className="lower-grid">
        <div className="card forecast" id="prediction-center"><Title title="PREDICTION CENTER" badge={result?"MODEL-DERIVED · 24H":"AWAITING MODEL"}/>{result?<><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Prediction forecast"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#1677ff" stopOpacity=".28"/><stop offset="1" stopColor="#1677ff" stopOpacity="0"/></linearGradient></defs><polygon points={`0,95 ${points} 100,95`} fill="url(#area)"/><polyline points={points} fill="none" stroke="#1677ff" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg><div className="forecast-stats"><b>{result.biogas.toFixed(1)}<small> m³/d<br/>Biogas</small></b><b>{result.methanePct.toFixed(1)}<small>%<br/>CH₄</small></b><b>{result.electricity.toFixed(1)}<small> kWh/d<br/>Electricity</small></b></div></>:<AwaitingPrediction text="The forecast will appear after the model returns a result."/>}</div>
        <div className="card health"><Title title="PROCESS HEALTH" badge={result?`${result.stability.toFixed(0)}% STABLE`:"AWAITING MODEL"}/>{result?<><div className="gauges"><Gauge label="COD removal" value={result.codRemoval}/><Gauge label="Gas stability" value={result.stability}/><Gauge label="Input coverage" value={result.confidence}/></div><div className="health-list"><span>Pressure <b>{result.pressure.toFixed(1)} mbar</b></span><span>H₂S prediction <b>{result.h2s.toFixed(0)} ppm</b></span><span>Data source <b>{health?.model.inputMode??"Manual input"}</b></span></div></>:<AwaitingPrediction text="Process-health calculations require a completed prediction."/>}</div>
        <div className="card history" id="data-audit"><Title title="RECENT SIMULATIONS" badge={`${history.length} RUNS`}/>{history.length?history.map((h,i)=><div className="history-row" key={i}><span><i className="ok">✓</i>{h.time}</span><b>{h.biogas.toFixed(1)} m³/d</b><em>{h.electricity.toFixed(0)} kWh</em></div>):<div className="no-history">Your model runs will appear here.</div>}<div className="iot-note"><span>◉</span><div><b>IoT integration pending</b><small>The current source is authenticated human input. Live sensor streaming is not enabled.</small></div></div></div>
      </section>
      <footer><span className={health?.services.api==="online"?"":"down"}><i></i> Cloud API {health?.services.api??"checking"}</span><span className={health?.services.model==="online"?"":"down"}><i></i> Model {health?.services.model??"checking"}</span><span className={health?.services.rag==="semantic"?"":"down"}><i></i> RAG {health?.services.rag??"checking"}</span><span><i></i> Knowledge: {health?`${health.knowledge.workbooks} workbooks · ${health.knowledge.chunks} chunks`:"checking"}</span><small>{health?`Checked ${new Date(health.checkedAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}`:"Checking backend status"} · Synthetic estimates, not plant validated</small></footer>
    </section>

    {chatOpen&&<div className="chat"><div className="chat-head"><div><span>✦</span><b>Aqua Copilot</b><small>Data-aware assistant</small></div><button onClick={()=>setChatOpen(false)}>×</button></div><div className="messages">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}>{m.text}</div>)}{chatBusy&&<div className="message ai typing"><i></i><i></i><i></i></div>}</div><div className="quick">{result&&<button onClick={applyBestSetpoints}>Apply best setpoints</button>}{quickQuestions.map(q=><button onClick={()=>ask(undefined,q)} key={q}>{q}</button>)}</div><form onSubmit={ask}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about this scenario…"/><button>➤</button></form></div>}
    {detailsOpen&&result&&<div className="details-backdrop" onClick={()=>setDetailsOpen(false)}><section className="details-modal" onClick={event=>event.stopPropagation()}><div className="details-head"><div><small>DYNAMIC PREDICTION REPORT</small><h2>Optimization details</h2></div><button onClick={()=>setDetailsOpen(false)}>×</button></div><div className="details-kpis"><Metric label="Biogas" value={`${result.biogas.toFixed(1)} m³/d`} delta={`${result.improvement>=0?"+":""}${result.improvement.toFixed(1)}% vs baseline`}/><Metric label="Methane" value={`${result.methanePct.toFixed(1)}%`} delta={`${result.methane.toFixed(1)} m³ CH₄/d`}/><Metric label="Electricity" value={`${result.electricity.toFixed(1)} kWh/d`} delta={`${result.generatorKw.toFixed(1)} kW generator`}/><Metric label="Carbon reduction" value={`${result.carbon.toFixed(2)} tCO₂e/d`} delta="Estimated"/></div><div className="details-table">{result.optimizationTargets.map((target,index)=><div key={target.label}><span>{index+1}. {target.label}</span><b className={target.value>=0?"positive":"negative"}>{target.value>=0?"+":""}{target.value.toFixed(1)}%</b></div>)}</div><p className="details-note"><b>{result.modelName}</b> · {result.modelFit}. Scenario coverage {result.confidence.toFixed(0)}% is an input-space score, not validated plant accuracy.</p><button className="details-apply" onClick={()=>{applyBestSetpoints();setDetailsOpen(false)}}>Apply modeled setpoints</button></section></div>}
    {settingsOpen&&auth.role==="admin"&&<div className="details-backdrop" onClick={()=>setSettingsOpen(false)}><section className="details-modal admin-modal" onClick={event=>event.stopPropagation()}><div className="details-head"><div><small>ADMIN CONTROL</small><h2>System and account status</h2></div><button onClick={()=>setSettingsOpen(false)}>×</button></div><div className="admin-summary"><div><span>Signed in as</span><b>{auth.username}</b><small>Administrator</small></div><div><span>Active model</span><b>{health?.model.name??"Checking"}</b><small>{health?`Version ${health.model.version}`:"Waiting for health check"}</small></div><div><span>Knowledge index</span><b>{health?`${health.knowledge.workbooks} workbooks`:"Checking"}</b><small>{health?`${health.knowledge.chunks} retrievable chunks`:"—"}</small></div></div><div className="readiness-list">{health?.checks.map(check=><div key={check.key}><i className={check.ready?"ready":"pending"}>{check.ready?"✓":"○"}</i><span><b>{check.label}</b><small>{check.ready?"Operational":"Not implemented"}</small></span><em>{check.weight}%</em></div>)??<AwaitingPrediction text="Loading live service checks…"/>}</div><div className="admin-actions"><button onClick={refreshHealth}>Refresh status</button><button className="signout" onClick={logout}>Sign out</button></div></section></div>}
  </main>
}

function LoginScreen({username,password,busy,error,onUsername,onPassword,onSubmit}:{username:string;password:string;busy:boolean;error:string;onUsername:(value:string)=>void;onPassword:(value:string)=>void;onSubmit:(event:FormEvent)=>void}){
  return <main className="login-shell"><section className="login-brand"><div className="login-logo"><span>◒</span><b>AQUAIVOLT<small>AI PLATFORM</small></b></div><div><em>SECURE OPERATIONS PORTAL</em><h1>Intelligent control starts with trusted access.</h1><p>Sign in to run biogas scenarios, review optimization guidance and consult the data-aware Copilot.</p></div><ul><li><i>✓</i> Protected model and RAG endpoints</li><li><i>✓</i> Role-aware admin diagnostics</li><li><i>✓</i> Human-approved operating recommendations</li></ul><small>Prototype environment · Synthetic scenario estimates</small></section><section className="login-panel"><form onSubmit={onSubmit}><div className="login-mark">✦</div><small>AQUAIVOLT COMMAND CENTER</small><h2>Welcome back</h2><p>Use your assigned administrator or operator account.</p><label><span>Username</span><input autoComplete="username" value={username} onChange={event=>onUsername(event.target.value)} placeholder="Enter username" required/></label><label><span>Password</span><input type="password" autoComplete="current-password" value={password} onChange={event=>onPassword(event.target.value)} placeholder="Enter password" required/></label>{error&&<div className="login-error">{error}</div>}<button disabled={busy}>{busy?<><span className="spinner"></span> Verifying access…</>:"Sign in securely →"}</button><div className="login-security"><span>●</span><div><b>Protected session</b><small>Credentials are verified by the server and are never stored in the browser.</small></div></div></form></section></main>
}

function AwaitingPrediction({text}:{text:string}){return <div className="awaiting"><span>◇</span><b>No static values</b><p>{text}</p></div>}

const targetIcons=["◈","ϟ","♨","◇","◉","♨","●"];
function OptimizationReport({result,benefitPoints,onDetails}:{result:Prediction;benefitPoints:string;onDetails:()=>void}){return <div className="optimization-report"><div className="optimization-columns"><section className="target-panel"><h3>Optimization Targets</h3><div className="target-list">{result.optimizationTargets.map((target,index)=><div className="target-row" key={target.label}><span className={`target-icon c${index}`}>{targetIcons[index]}</span><b>{target.label}</b><em className={target.value>=0?"positive":"negative"}>{target.value>=0?"+":""}{target.value.toFixed(1)}% <i>{target.value>=0?"↑":"↓"}</i></em></div>)}</div></section><div className="optimization-side"><section className="rec-panel"><h3>AI Recommendations</h3><div className="compact-recs">{result.recommendations.map((recommendation,index)=><div className="compact-rec" key={recommendation.title}><span>{index+1}</span><div><b>{recommendation.title}</b><small>{recommendation.detail}</small></div><em>{recommendation.impact?`+${recommendation.impact.toFixed(1)}%`:"Check"}</em></div>)}</div></section><section className="benefit-panel"><div><small>Overall Benefit vs Baseline</small><b className={result.overallBenefit>=0?"positive":"negative"}>{result.overallBenefit>=0?"+":""}{result.overallBenefit.toFixed(1)}%</b><span>Same baseline as optimization gain</span></div><svg viewBox="0 0 100 40" preserveAspectRatio="none" aria-label="Overall benefit trend"><polyline points={benefitPoints} fill="none" stroke={result.overallBenefit>=0?"#128a70":"#df5d54"} strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg></section></div></div><button className="optimization-details" onClick={onDetails}>View Optimization Details</button></div>}

function Title({title,badge}:{title:string;badge:string}){return <div className="card-title"><h2>{title}</h2><span>{badge}</span></div>}
function Kpi({label,value,color,note}:{label:string;value:string;color:string;note:string}){return <div className="kpi card"><div className={`ring ${value.length>5?"wide-value":""}`} style={{"--color":color} as React.CSSProperties}><b>{value}</b></div><div><span>{label}</span><small>{note}</small><i style={{background:color}}></i></div></div>}
function Field({label,value,unit,onChange,options,step,min,max}:{label:string;value:string|number;unit?:string;onChange:(v:string)=>void;options?:string[];step?:string;min?:number;max?:number}){return <label className="field"><span>{label}</span><div>{options?<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select>:<input type="number" step={step||"1"} min={min} max={max} value={value} onChange={e=>onChange(e.target.value)}/>} {unit&&<em>{unit}</em>}</div></label>}
function Metric({label,value,delta}:{label:string;value:string;delta:string}){return <div className="metric"><span>{label}</span><b>{value}</b><small>{delta} ↗</small></div>}
function Gauge({label,value}:{label:string;value:number}){return <div><div className="gauge" style={{"--p":`${Math.max(0,Math.min(100,value))*3.6}deg`} as React.CSSProperties}><b>{value.toFixed(0)}%</b></div><span>{label}</span></div>}
function AgentSteps(){return <div className="agent-steps"><div className="agent-orb">✦</div><b>Optimization agent is working</b>{["Validating inputs","Running linear prediction model","Testing safe setpoint changes","Writing operator recommendations"].map((s,i)=><span key={s} style={{animationDelay:`${i*.18}s`}}><i>✓</i>{s}</span>)}</div>}
